name: piix_mobile
description: A piix application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  #Connects to firebase firestore
  cloud_firestore: ^5.6.5
  #An HTTP Request api
  dio: ^5.1.2
  #Allows to obscure and encrypt variables
  envied: ^0.3.0+3
  #A firebase analytics api
  firebase_analytics: ^11.4.4
  #A firebase auth api
  firebase_auth: ^5.5.1
  #A firebase central api to control the firebase instance
  firebase_core: ^3.12.1
  #A firebase crashlytics api
  firebase_crashlytics: ^4.3.4
  #A firebase storage api
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  #Allows to view and cache pdf files
  # flutter_cached_pdfview: ^0.4.1
  flutter_localizations:
    sdk: flutter
  #State management and cache handler
  flutter_riverpod: ^2.3.2
  #Draw SVG files using Flutter
  flutter_svg: ^1.1.6
  #Controls screen and font size
  flutter_screenutil: ^5.9.0
  #Allows to navigate the app with Flutter Navigator 2.0
  go_router: ^13.2.0
  #Allows to control localized time, dates, and even strings
  intl: any
  #Allows to annotate classes for automatic json serialization generation
  json_annotation:
    ^4.8.0
    #Allows to save images in gallery
  json_serializable: ^6.5.4
  #A logger library for logs
  logger: ^1.1.0
  #Allows to create riverpod providers
  riverpod: ^2.5.1
  #Allows to annotate certain properties as riverpod instances
  riverpod_annotation: ^2.0.2
  #Introduces Reactive X programming
  rxdart: ^0.27.7
  #Allows to persist data in local with an object storage in ios and android
  sembast: ^3.6.0
  #Allows to persist data in local with an object storage in web
  sembast_web: ^2.2.0
  #Allows to persist data between sessions
  shared_preferences: ^2.5.2

dev_dependencies:
  #Used to run envied in build runner
  envied_generator: ^0.3.0+3
  flutter_test:
    sdk: flutter
  #Creates a mock class to be used in testing
  mocktail: ^1.0.3
  #Runs code generator
  build_runner: ^2.4.8
  #Used to keep code linter
  custom_lint:
  #used to run integration tests
  integration_test:
    sdk: flutter
  #Used to tun riverpod with build runner
  riverpod_generator: ^2.3.3
  #Executes cleaning of riverpod classes
  riverpod_lint: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/svgs/
    - assets/svgs/app_brand/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 900
    - family: PiixIcons
      fonts:
        - asset: assets/icons/PiixIcons.ttf
